### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by kyrias** [DTVD/rainbowstream#109]
Hello,

Could you tag releases to make packaging rainbow stream easier?

**Comment by DTVD** [comment]
Hello @kyrias. I am releasing RainbowStream through `pip` - the official Python package manager. The version on pip contains the CONFIG KEY, but this repo on Github is not. So packaging this repo on a tag release will not provide a runnable version of RainbowStream.

**Comment by kyrias** [comment]
Fair enough, though you can also upload release tarballs/zips to GitHub.

---

Anyway, tags make making a -git package nicer too, since ``git-describe`` will give sensible output, and will also help working with the history to find eg a bug introduced in some commit since the last release.
