### ISSUE TITLE
No stream update

### ISSUE THREAD

**Issue by bullyliit** [DTVD/rainbowstream#117]
I finally got everything up. But this always comes up. It also shows up when I try `switch mine` command, but with an incremented number on the thread. I've been using Linux for a couple of weeks now and a total newbie.

![2015-07-08-212410_1024x600_scrot](https://cloud.githubusercontent.com/assets/12786577/8571283/4b2173ee-2575-11e5-84cf-15ec96d55f1b.png)

**Comment by bullyliit** [comment]
I finally figured it out. Turns out, I did not set my system time (time zone, local time, and hardware time) correctly. Sorry. I got it working now.

**Comment by DTVD** [comment]
Hi @bullyliit I will take a further look into this issue. Thanks for reporting :)
