### ISSUE TITLE
IMAGE_ON_TERM reverts to 'false' on start

### ISSUE THREAD

**Issue by achilleas-k** [DTVD/rainbowstream#136]
Just as the title says. Upon launching rainbowstream, IMAGE_ON_TERM immediately reverts to `false` from `true` in the config file. If I enable it while the program is running, it works. The setting remains `true` in the config file after I quit, but as soon as I launch, it switches back to `false`.
I can see the change happening with `watch -d cat ~/.rainbow_conf`.

EDIT: Launching with `-iot` works around the issue, but the config setting should persist.

**Comment by DTVD** [comment]
This is improved in 1.3.2. Thanks!
