### ISSUE TITLE
Feature request: Limit tweets per second

### ISSUE THREAD

**Issue by pr0letariat** [DTVD/rainbowstream#140]
Would be nice to be able to limit the tweets per second (rather than see them live) so those of us who follow a lot of people can read the tweets more easily.

**Comment by poulp** [comment]
+1

**Comment by tuqueque** [comment]
What I do to not lose track of new vs read tweets is: scroll-up a few lines the Terminal stream (I use qterminal)... That way, when new tweets arrive, they are placed down the stream as usual, but they don't move up my stream and I just simply scroll down manually when I want to read my tweets at the pace I choose... I hope it makes sense. Is an almost stupid "trick", but it works for me until a proper unread/read feature implementation arrives in Rainbowstream.

**Comment by DTVD** [comment]
Hi @pr0letariat and @tuqueque 

Take a look at https://github.com/DTVD/rainbowstream/issues/79. There is a config option `STREAM_DELAY` as well as `p` and `r` command.
