### ISSUE TITLE
Installation fails at pillow

### ISSUE THREAD

**Issue by mogoh** [DTVD/rainbowstream#143]
As the Title says.

Here is the error:
```
error: command 'i686-linux-gnu-gcc' failed with exit status 1
 
----------------------------------------
Cleaning up...
Command /home/mogoh/opt/rbs/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-l_usbjdt/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7b2dx04g-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mogoh/opt/rbs/include/site/python3.4 failed with error code 1 in /tmp/pip-build-l_usbjdt/Pillow
Storing debug log for failure in /home/mogoh/.pip/pip.log
```
Here is the complete output:
http://pastebin.com/6MwtCtCP

uname -a:
```
(rbs)mogoh@annalee:~/opt$ uname -a
Linux annalee 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:38:40 UTC 2015 i686 i686 i686 GNU/Linux
```

**Comment by DTVD** [comment]
Hi, I think problem is the line
```
error: command 'i686-linux-gnu-gcc' failed with exit status 1
```

Maybe you should install python-dev on your Ubuntu like this link
http://stackoverflow.com/questions/11094718/error-command-gcc-failed-with-exit-status-1-while-installing-eventlet

**Comment by mogoh** [comment]
It suddently worked, but I don't know why. python-dev was already insalled. Maybe it was a missing reboot? I don't know. Thank you for your help. This can be closed now.

**Comment by DTVD** [comment]
Glad that it worked. But I don't think RS need a reboot to install correctly. I will close this issue
