### ISSUE TITLE
"Chaining" tweets?

### ISSUE THREAD

**Issue by nevillepark** [DTVD/rainbowstream#163]
On Twitter you can link tweets together like a conversation thread by replying to yourself and deleting your handle. ([Example](https://twitter.com/neville_park/status/707597740914696192).) Would it be possible to add this feature to Rainbowstream, maybe as a "manual reply" where the handle isn't automatically prepended?

**Comment by b3yond** [comment]
That would be super easy actually - you'd only have to add a few lines on line 620, to erase "@"+$user in the $status in such a case.
compare $user with your own username, pass a different $status if they match.

I'd do it myself, unfortunately I don't know how the username is stored in rainbowstream, couldn't find it.

**Comment by b3yond** [comment]
ok, found it and commited. 
pull request: https://github.com/DTVD/rainbowstream/pull/207

**Comment by b3yond** [comment]
This issue can be closed, feature is added in 1.3.7
