### ISSUE TITLE
Create changelog and add git tags

### ISSUE THREAD

**Issue by koobs** [DTVD/rainbowstream#187]
I'm updating the [rainbowstream FreeBSD Port](https://www.freshports.org/net/py-rainbowstream/) to 1.3.5 and need a quick way to identify the changes between versions, so I can include a change list or URL reference in the commit log for our users.

This content would also be useful for adding to the website/documentation if so desired, and also provide an easy way for users to determine changes between versions.

While we're on versions, can git tags be added to the repository? Not least because its good practice, but also so at a minimum, any one can compare commits between tags to identify whats changed between versions.

Edit: git (and release) version tags as format `x.y.z` ([SemVer](http://semver.org/)) please!

Thanks!

**Comment by DTVD** [comment]
Hello! Thanks for your work
I will create a tag for current version (1.3.5) and create a tag for every new update from now on.

Cheer.
