### ISSUE TITLE
Odd characters in Windows Linux Subsystem

### ISSUE THREAD

**Issue by coreyog** [DTVD/rainbowstream#188]
![image](https://cloud.githubusercontent.com/assets/2836207/17787376/1c36bf8c-6546-11e6-8c78-6164f923d4a9.png)

It's most visible in images but also visible in the tweet info. The likes and retweets icons are not properly drawn. I imagine this is more an issue with WLS terminal emulation mode. The coloration is also a little off because of this.

This issue aside, it seems very stable in WLS.

**Comment by DTVD** [comment]
Thanks for report.

It might be problem with Unicode display on WLS terminal and currently i can not do anything with it.  You can try another terminal for better display :smile:
