### ISSUE TITLE
No streaming of my timeline with 'Problem accessing '/1.1/user.json'. Reason: Unauthorized' message

### ISSUE THREAD

**Issue by rsfo78hpge** [DTVD/rainbowstream#192]
HI,
Whenever I launch rainbowstream I get this message:

We have connection problem with twitter stream API right now :(
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>
<body>
<h2>HTTP ERROR: 401</h2>
<p>Problem accessing '/1.1/user.json'. Reason:
<pre>    Unauthorized</pre>
</body>
</html>

edit - (or at least the unformatted command line version of this message!)

I tried various combinations of deleting ~/.rainbowstream_oauth to recreate the token, re-installing virtualenv and or rainbowstream with sudo or just as USER, eventually settling on using this tutorial to install virtualenv: http://www.simononsoftware.com/virtualenv-tutorial-part-2/ followed by installing rainbowstream as per the instructions here and elsewhere. 

(For the record I do not have a /root/.rainbowstream_oauth or /root/.rainbow_config.json file so my guess is this isn't be the issue).

Although I get the message above when initiating rainbowstream, I can do everything within rainbowstream (tweet, retweet, view my timeline with the home command etc) as per the manual. The only issue I experience is that I don't get the ongoing stream of my timeline.

I made a couple of alterations to my ~/.rainbow_config.json which hasn't altered the problem behaviour in any way, but I've included it below just in case  you see something.

This second I have just undergone the process of deactivating rainbowstream in twitter, followed by deleting /.rainbowstream_oauth then started up rainbowstream in order to recreate the token, etc, and I still have the same issue. 

Any ideas?

thanks for your help!

.rainbow_config.json file just in case: 

{
    "HEARTBEAT_TIMEOUT": 120,⋅
    "IMAGE_ON_TERM": true,⋅
    "IMAGE_RESIZE_TO_FIT": true,⋅
    "THEME": "base16",⋅
    "ASCII_ART": false,⋅
    "HIDE_PROMPT": false,⋅
    "PREFIX": "#owner#place#me#keyword",⋅
    "SEARCH_TYPE": "recent",⋅
    "SEARCH_MAX_RECORD": 100,⋅
    "HOME_TWEET_NUM": 100,⋅
    "RETWEETS_SHOW_NUM": 5,⋅
    "CONVERSATION_MAX": 30,⋅
    "QUOTE_FORMAT": "#comment RT #owner: #tweet",⋅
    "THREAD_META_LEFT": "(#id) #clock",⋅
    "THREAD_META_RIGHT": "#clock (#id)",⋅
    "THREAD_MIN_WIDTH": 20,⋅
    "NOTIFY_FORMAT": "  #source_user #notify #clock",⋅
    "MESSAGES_DISPLAY": 5,⋅
    "TREND_MAX": 10,⋅
    "LIST_MAX": 5,⋅
    "ONLY_LIST": [],⋅
    "IGNORE_LIST": [],⋅
    "HISTORY_FILENAME": "completer.hist",⋅
    "IMAGE_SHIFT": 2,⋅
    "IMAGE_MAX_HEIGHT": 90,⋅
    "STREAM_DELAY": 0,⋅
    "USER_DOMAIN": "userstream.twitter.com",⋅
    "PUBLIC_DOMAIN": "stream.twitter.com",⋅
    "SITE_DOMAIN": "sitestream.twitter.com",⋅
    "FORMAT": {
        "TWEET": {
            "CLOCK_FORMAT": "%Y/%m/%d %H:%M:%S",⋅
            "DISPLAY": "\n  #name #nick #clock \n  \u267a:#rt_count \u2665:#fa_count id:#id via #client #fav\n  #tweet"
        },⋅
        "MESSAGE": {
            "CLOCK_FORMAT": "%Y/%m/%d %H:%M:%S",⋅
            "DISPLAY": "\n  #sender_name #sender_nick #to #recipient_name #recipient_nick :\n  #clock message_id:#id\n  #message"
        }
    },⋅
    "POCKET_SUPPORT": false
}

**Comment by DTVD** [comment]
Hi. Thanks for report.

As far as I can see that you can use normal command, your oauth setting/process is correct for sure. The problem may comes from Twitter Stream API itself. 

Here is my suggest:

* Double check rainbowstream on your Twitter account setting: https://twitter.com/settings/applications. This is sample screenshot of mine ![](https://i.gyazo.com/76588b230056a4cf4f8177ac0449caa6.png)
* Try another Twitter client to see if Twitter Stream API work with them also or not.
* Take a break, wait for a while and try again :smile:

**Comment by rsfo78hpge** [comment]
Hi, I tried another twitter client, which was unable to fetch the token for authorisation. It suggested (amongst other things) checking my system clock. For some reason my ntp service was not running - I started it and now rainbowstream works fine! 
Thanks for the app, the reply, and pointing me in the right direction!
