### ISSUE TITLE
"requests==2.5.3" why is this version locked? in setup.py 

### ISSUE THREAD

**Issue by violetina** [DTVD/rainbowstream#200]
I tested 2.11.1, 2.9.1 and 2.8.1 
it works till version 2.8.1 
so maybe <= 2.81 might be better
2.5.3 is quite old

**Comment by DTVD** [comment]
Thanks, will test and update version

**Comment by DTVD** [comment]
Request 2.6 introduced `InsecurePlatformWarning` for users of python prior to 2.7.9 with stock SSL modules. There are extra packages required to get rid of that warning but there is no guarantee for all platform, so I will choose to leave Requests locked at 2.5 at this time.
http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

**Comment by untitaker** [comment]
Please reopen, pinning to a particular version is not acceptable when packaging rainbowstream for a particular distribution. Also the StackOverflow answer contains a way to disable that warning without extra packages.

**Comment by onhernandes** [comment]
Please reopen.
I'm having some trouble because this is causing conflict with docker/docker-compose, with needs requests >= 2.6, also, other CLIs
