### ISSUE TITLE
Character count

### ISSUE THREAD

**Issue by kura** [DTVD/rainbowstream#58]
It would be cool to have some kind of character count display and update while using `t`, `rep`, `mes` and `q`.

I might implement this feature myself though and submit a PR.

**Comment by Tenzer** [comment]
An easier alternative might be to just count the amount of characters before sending the tweet, and then printing the count along with a message if it goes above the 140 chars.

**Comment by kramimus** [comment]
Yeah, this would be nice, right now if you go over the char count, you just get:

"OMG something is wrong with Twitter right now."

**Comment by the-solipsist** [comment]
TTYtter used to use [Term::Readline (for Perl)](http://search.cpan.org/~ckaiser/Term-ReadLine-TTYtter-1.4/). It might be worthwhile considering something [similar for Python](https://docs.python.org/2/library/readline.html)
