### ISSUE TITLE
Tweets from the past in the stream

### ISSUE THREAD

**Issue by mmk2410** [DTVD/rainbowstream#81]
Through the stream I always get tweets which where tweeted a few hours ago. Only if I enter 'home' I get the recent tweets.

Rainbowstream Version: 1.2.5
Python Version: 3.4.2
My OS: Arch Linux

**Comment by mmk2410** [comment]
No (after one and a half hour) the stream shows the most recent tweets.

**Comment by DTVD** [comment]
I'm sorry maybe it has problem with stream connection. 
Can u reload your stream with `switch mine` and see if the stream show tweets correctly ?

**Comment by mmk2410** [comment]
At the moment it all works just fine. But if I have the problem again I will try the `switch mine` command and notify you about the results.

**Comment by DTVD** [comment]
Thanks !
