### ISSUE TITLE
Tweet marker support

### ISSUE THREAD

**Issue by asbjornenge** [DTVD/rainbowstream#85]
Not really sure how it would work in a rainbowstream context, but a timeline sync is an essential feature for me since I read twitter on multiple devices and have quite a busy feed. One idea could be that if tweetmarker is enabled <code>home 3</code> would load 3 new tweets from last mark. Or home would always pull up to the last read mark and a new load command would pull in new tweets. I dunno, just ideas :smile_cat:

**Comment by DTVD** [comment]
I see, this is like some *tag* mark on the stream timeline. But if other client (other devices client) doesn't support such feature, is it really helpful on just RainbowStream ?
For example, in case you can set a mark at RS, you can only browse tweets relate to that mark inside RS, right ?

**Comment by asbjornenge** [comment]
Lots of other clients do support it. Uhm, it's just a way to sync "last read tweet" between clients. So if I do *home* on RS it should push the last seen tweet to TM. And when I open whateverapp that supports TM on my phone, it would automatically scroll me to this tweet in the timeline.

If a client does not support it then it just operates "normally" showing the whole timeline and never pushing any information to TM (this is what currently makes it quite annoying to use RS for me, since tweets I've already read on RS I have to manually scroll by on my other devices, and of course the fact that there is no way for me to tell RS where I want to start reading from)

**Comment by DTVD** [comment]
Maybe those clients are using [Tweet maker](http://tweetmarker.net/) ? Can you give me for example what client you are using is supporting this :)

**Comment by asbjornenge** [comment]
@DTVD that is the one I'm referring to. It's called tweet marker, not maker :stuck_out_tongue: There is a list of clients supporting it on the website there. I'm using Tweetbot on iOS mostly these days, but have been using Twitterific i the past.

**Comment by DTVD** [comment]
Thanks. Just discovered this topic on another FOSS project : 
[Tweet marker supports on t](https://github.com/sferik/t/issues/173)

Like @sferik pointed out. an FOSS has no way to hide a 25$-per-month secret key. 
Maybe the best way to use that feature is purchasing a license yourself and add Tweet marker API support directly to a folk of RS.
If you decide to go that way, I will help out any problem with RS source code :smile:

**Comment by asbjornenge** [comment]
@DTVD Ah, I didn't know it was a paid service! Maybe I'll make a free service instead ;-)
