### ISSUE TITLE
Twitter shortened URLs ending in . are opened with .

### ISSUE THREAD

**Issue by queuebit** [DTVD/rainbowstream#93]
[Offending tweet](https://twitter.com/rockymtnruby/status/573146707124346881) where when I run `open X` it opened with url of <https://t.co/ndo4ZfC1DW.>.

Just putting this here for now. I would love to make a PR, but not sure where to start and if a fix is possible since some urls include the `.`.

**Comment by DTVD** [comment]
Hi @queuebit. Thanks for report :+1: 
I'm not sure why only url in this tweet can not be parsed correctly. Will look further into this

**Comment by queuebit** [comment]
Adding [another tweet](https://twitter.com/DarkSkyApp/status/575308659804225536) that has the same issue, it opened with url of <http://t.co/KPZr63poP7).>

**Comment by Tenzer** [comment]
This should be fixed with 685c4aa.
