### ISSUE TITLE
Relative timestamps?

### ISSUE THREAD

**Issue by nevillepark** [DTVD/rainbowstream#94]
It would be nice to see recent timestamps in a relative format ("2 minutes ago", "3 months ago", etc.) rather than strftime. Would it be possible to [add a function like this](http://stackoverflow.com/a/5164027)?

**Comment by DTVD** [comment]
Hi @nevillepark, RS already has humanization timestampe:
![](http://i.gyazo.com/d2fcd9156b7e81a308da55074a9aca17.png)

**Comment by nevillepark** [comment]
Huh. It must be something in my locale settings then! Thanks.

**Comment by nevillepark** [comment]
After some poking around, it's because Arrow doesn't support en_CA. Changed to en_US and now mention timestamps are humanized, but not in the regular timeline.
