### ISSUE TITLE
FreeBSD 10.1 install problem

### ISSUE THREAD

**Issue by CanOfBees** [DTVD/rainbowstream#95]
Hi DTVD,

this is a wonderful Twitter application you've shared - thank you very much. I'm having some problems getting it working on FreeBSD 10.1 - it installed fine on a PC-BSD 10.1 system - and I'm not sure where my problems are.

I did the following as root: `# pip install rainbowstream` without any errors or dependency problems.

As a regular user:
```
> rainbowstream
You are running latest version (1.2.7)
Hi there! We're gonna get you all set up to use Rainbow Stream.
There seems to be a connection problem.
You might want to check your proxy settings (host, port and type)!
```

I'm not using a proxy and I'm pretty sure that it isn't a firewall problem on my FreeBSD install, unless Rainbow Stream uses an odd port to try talking to Twitter?

I've tried uninstalling/reinstalling without any success.
Any suggestions?

Thank you for your time and trouble!

**Comment by DTVD** [comment]
Hi @CanOfBees Thanks for report!
RS doesn't use some special port to connect to Twitter. Maybe Twitter API just got unstable during a while.
Can you try again tomorrow and if this problem still there please let me know

**Comment by koobs** [comment]
@CanOfBees See #180 

Can you try the port/pkg (or latest rainbowstream versions) and let us know if you can still reproduce

**Comment by CanOfBees** [comment]
Hi @koobs - thanks for the response. Somewhere along the way I think I reinstalled with `pip` and things  started working again. I just reinstalled with `pkg` and everything started okay there, too. I removed the pkg and built the port: it just works from there, too.

Let me know if you'd like me to test anything else: I probably didn't make as clean a slate as I could have, so I'm happy to rebuild if it would be useful.

Cheers!

**Comment by koobs** [comment]
@CanOfBees Lovely, thank you for testing them :)

Only thing I'd suggest is removing/deleting rainbowstream (both `pip uninstall` and `pkg delete`), then looking in `/usr/local/lib/pythonX.Y/site-packages` to look for leftovers (`*rainbow*`) that may cause issues/conflicts in the future. If/when it's clear, reinstall from ports/packages and enjoy

Also, can this issue now be closed?
